# Generated by Django 4.2.6 on 2023-11-03 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('from_url', models.CharField(help_text='Enter from url', max_length=300)),
                ('to_url', models.CharField(help_text='Enter to url', max_length=300)),
                ('status_code', models.IntegerField(blank=True, choices=[(301, '301 Moved Permanently'), (307, '307 Temporary Redirect')], default='standard', help_text='Redirect type', max_length=20, null=True, verbose_name='Redirect type')),
                ('is_regx', models.BooleanField(default=False, help_text='Is this regx?')),
                ('note', models.CharField(blank=True, help_text='Enter note', max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta Description', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Meta Keywords', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta Title', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta Description', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Meta Keywords', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta Title', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_description',
            field=models.TextField(blank=True, help_text='Meta Description', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Meta Keywords', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='meta_title',
            field=models.CharField(blank=True, help_text='Meta Title', max_length=120, null=True),
        ),
    ]
