# Generated by Django 4.2.6 on 2023-11-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='description',
            new_name='excerpt',
        ),
    ]
