# Generated by Django 4.2.6 on 2023-10-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Meta Title', max_length=300, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Meta Keywords', max_length=300, null=True)),
                ('title', models.CharField(help_text='Enter title', max_length=300)),
                ('slug', models.SlugField(help_text='Enter slug', max_length=150, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Enter excerpt', max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order', null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('publish_status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('LIVE', 'LIVE'), ('DELETED', 'DELETED')], default='DRAFT', help_text='Select publish status', max_length=20, null=True, verbose_name='Publish status')),
                ('content', models.TextField(help_text='Post content', null=True)),
                ('active', models.BooleanField(blank=True, default=False, help_text='Active')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
    ]
