# Generated by Django 4.2.6 on 2023-10-31 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0002_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='page',
            name='slug',
        ),
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.CharField(default=None, help_text='Enter url', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
