# Generated by Django 4.2.6 on 2023-11-11 16:48

import bloggy.models.page
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0002_rename_description_category_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='logo',
            new_name='thumbnail',
        ),
        migrations.AddField(
            model_name='page',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=bloggy.models.page.image_upload_path),
        ),
    ]
