# Generated by Django 4.2.6 on 2023-11-03 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0002_redirectrule_alter_course_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectrule',
            name='status_code',
            field=models.IntegerField(blank=True, choices=[(301, '301 Moved Permanently'), (307, '307 Temporary Redirect')], default='standard', help_text='Redirect type', null=True, verbose_name='Redirect type'),
        ),
    ]
