# Generated by Django 4.2.6 on 2023-11-03 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0003_alter_redirectrule_status_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirectrule',
            name='is_regx',
            field=models.BooleanField(default=False, help_text='Is this regx?', null=True),
        ),
    ]
