# Generated by Django 4.2.7 on 2023-11-17 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0003_rename_logo_category_thumbnail_page_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redirectrule',
            name='is_regx',
        ),
    ]
