# Generated by Django 4.2.7 on 2023-12-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0004_remove_redirectrule_is_regx'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='template_type',
            field=models.CharField(blank=True, choices=[('naked', 'Naked'), ('default', 'Default'), ('wide', 'Wide')], default='default', help_text='Template type', max_length=20, null=True, verbose_name='Template type'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[['post', 'Post']], default='article', help_text='Post type', max_length=20, null=True, verbose_name='Post type'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post_type',
            field=models.CharField(choices=[['post', 'Post']], help_text='Select content type', max_length=20, verbose_name='Content type'),
        ),
    ]
