# Generated by Django 4.2.6 on 2023-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0004_alter_redirectrule_is_regx'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='github_link',
            field=models.CharField(blank=True, help_text='Github project link', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[['post', 'Post'], ['lesson', 'Lesson']], default='article', help_text='Post type', max_length=20, null=True, verbose_name='Post type'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post_type',
            field=models.CharField(choices=[['post', 'Post'], ['lesson', 'Lesson']], help_text='Select content type', max_length=20, verbose_name='Content type'),
        ),
    ]
