# Generated by Django 4.2.7 on 2024-01-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0006_alter_page_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'Advance')], default='easy', help_text='Select difficulty', max_length=20, null=True, verbose_name='Difficulty level'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(blank=True, choices=[['post', 'Post'], ['lesson', 'Lesson']], default='article', help_text='Post type', max_length=20, null=True, verbose_name='Post type'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='post_type',
            field=models.CharField(choices=[['post', 'Post'], ['lesson', 'Lesson']], help_text='Select content type', max_length=20, verbose_name='Content type'),
        ),
    ]
