# Generated by Django 4.2.6 on 2023-11-07 00:10

import bloggy.models.quiz
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0006_category_meta_description_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='Meta Title', max_length=120, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Meta Description', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Meta Keywords', max_length=300, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Enter title', max_length=300)),
                ('slug', models.SlugField(help_text='Enter slug', max_length=150, unique=True)),
                ('excerpt', models.CharField(blank=True, help_text='Enter excerpt', max_length=500, null=True)),
                ('display_order', models.IntegerField(default=0, help_text='Display order', null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('publish_status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('LIVE', 'LIVE'), ('DELETED', 'DELETED')], default='DRAFT', help_text='Select publish status', max_length=20, null=True, verbose_name='Publish status')),
                ('difficulty', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advance', 'advance')], default='easy', help_text='Select difficulty', max_length=20, null=True, verbose_name='Difficulty level')),
                ('is_featured', models.BooleanField(default=False, help_text='Should this story be featured on site?')),
                ('content', models.TextField(help_text='Post content', null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=bloggy.models.quiz.upload_thumbnail_image)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='bloggy.category')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='UserQuizScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('score', models.FloatField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggy.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, help_text='Enter description', null=True)),
                ('explanation', models.TextField(blank=True, help_text='Enter explanation', null=True)),
                ('type', models.CharField(blank=True, choices=[('binary', 'binary'), ('multiple', 'multiple')], default='binary', help_text='Select type of question', max_length=20, null=True, verbose_name='Question type')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bloggy.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloggy.quizquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['slug', 'publish_status'], name='bloggy_quiz_slug_d36048_idx'),
        ),
    ]
