# Generated by Django 4.2.7 on 2024-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0007_alter_post_difficulty_alter_post_post_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_new_content',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_news_updates',
            field=models.BooleanField(default=True),
        ),
    ]
