# Generated by Django 4.2.6 on 2023-11-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0007_quiz_userquizscore_quizquestion_quizanswer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.IntegerField(default='1', help_text='Duration in minutes. For articles, it will be calculated automatically.'),
        ),
    ]
