# Generated by Django 4.2.6 on 2023-11-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0008_quiz_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redirectrule',
            old_name='to_url',
            new_name='destination',
        ),
        migrations.RenameField(
            model_name='redirectrule',
            old_name='from_url',
            new_name='source',
        ),
    ]
