# Generated by Django 4.2.7 on 2024-01-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0008_user_receive_new_content_user_receive_news_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(help_text='Enter title', max_length=300)),
                ('url', models.CharField(help_text='Enter url', max_length=150, unique=True)),
                ('content', models.JSONField()),
                ('content_html', models.TextField(help_text='Newsletter content', null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('publish_status', models.CharField(blank=True, choices=[('DRAFT', 'DRAFT'), ('LIVE', 'LIVE'), ('DELETED', 'DELETED')], default='DRAFT', help_text='Select publish status', max_length=20, null=True, verbose_name='Publish status')),
            ],
            options={
                'verbose_name': 'Newsletter',
                'verbose_name_plural': 'Newsletters',
            },
        ),
        migrations.DeleteModel(
            name='RedirectRule',
        ),
    ]
