# Generated by Django 4.2.7 on 2024-01-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggy', '0009_newsletter_delete_redirectrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='send_to_all',
            field=models.BooleanField(default=False, help_text='Send to all'),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='send_to_users_only',
            field=models.BooleanField(default=False, help_text='Send to registered users only'),
        ),
    ]
